{
    "items": [
        {
            "deviceId": "1ed803e3-f507-ac3f-0ac6-e7bad88f2339",
            "name": "[washer] Samsung",
            "label": "Washer",
            "manufacturerName": "Samsung Electronics",
            "presentationId": "DA-WM-WM-01011",
            "deviceManufacturerCode": "Samsung Electronics",
            "locationId": "e0cc1d23-ceba-40aa-9121-db1134002353",
            "ownerId": "50ed6115-a30c-a7d6-af51-9e96fc5ac1b5",
            "roomId": "568ea0cd-e641-44c4-9a61-3c5c5748e496",
            "deviceTypeName": "Samsung OCF Washer",
            "components": [
                {
                    "id": "main",
                    "label": "main",
                    "capabilities": [
                        {"id": "execute", "version": 1},
                        {"id": "ocf", "version": 1},
                        {"id": "powerConsumptionReport", "version": 1},
                        {"id": "refresh", "version": 1},
                        {"id": "remoteControlStatus", "version": 1},
                        {"id": "demandResponseLoadControl", "version": 1},
                        {"id": "switch", "version": 1},
                        {"id": "washerOperatingState", "version": 1},
                        {"id": "custom.disabledCapabilities", "version": 1},
                        {"id": "custom.dryerDryLevel", "version": 1},
                        {"id": "custom.energyType", "version": 1},
                        {"id": "custom.jobBeginningStatus", "version": 1},
                        {"id": "custom.supportedOptions", "version": 1},
                        {"id": "custom.washerAutoDetergent", "version": 1},
                        {"id": "custom.washerAutoSoftener", "version": 1},
                        {"id": "custom.washerRinseCycles", "version": 1},
                        {"id": "custom.washerSoilLevel", "version": 1},
                        {"id": "custom.washerSpinLevel", "version": 1},
                        {"id": "custom.washerWaterTemperature", "version": 1},
                        {"id": "samsungce.autoDispenseDetergent", "version": 1},
                        {"id": "samsungce.autoDispenseSoftener", "version": 1},
                        {"id": "samsungce.detergentOrder", "version": 1},
                        {"id": "samsungce.detergentState", "version": 1},
                        {"id": "samsungce.deviceIdentification", "version": 1},
                        {"id": "samsungce.driverVersion", "version": 1},
                        {"id": "samsungce.detergentAutoReplenishment", "version": 1},
                        {"id": "samsungce.softenerAutoReplenishment", "version": 1},
                        {"id": "samsungce.flexibleAutoDispenseDetergent", "version": 1},
                        {"id": "samsungce.softwareUpdate", "version": 1},
                        {"id": "samsungce.kidsLock", "version": 1},
                        {"id": "samsungce.softenerOrder", "version": 1},
                        {"id": "samsungce.softenerState", "version": 1},
                        {"id": "samsungce.washerBubbleSoak", "version": 1},
                        {"id": "samsungce.washerCycle", "version": 1},
                        {"id": "samsungce.washerCyclePreset", "version": 1},
                        {"id": "samsungce.washerDelayEnd", "version": 1},
                        {"id": "samsungce.washerFreezePrevent", "version": 1},
                        {"id": "samsungce.washerLabelScanCyclePreset", "version": 1},
                        {"id": "samsungce.washerOperatingState", "version": 1},
                        {"id": "samsungce.washerWashingTime", "version": 1},
                        {"id": "samsungce.washerWaterLevel", "version": 1},
                        {"id": "samsungce.washerWaterValve", "version": 1},
                        {"id": "samsungce.welcomeMessage", "version": 1},
                        {"id": "samsungce.waterConsumptionReport", "version": 1},
                        {"id": "samsungce.clothingExtraCare", "version": 1},
                        {"id": "sec.diagnosticsInformation", "version": 1},
                        {"id": "sec.wifiConfiguration", "version": 1},
                    ],
                    "categories": [{"name": "Washer", "categoryType": "manufacturer"}],
                },
                {"id": "hca.main", "label": "hca.main", "capabilities": [{"id": "hca.washerMode", "version": 1}], "categories": [{"name": "Other", "categoryType": "manufacturer"}]},
            ],
            "createTime": "2023-11-15T23:53:07.248Z",
            "profile": {"id": "8490e52f-7584-368b-a48c-fa0ec8c1c0bf"},
            "ocf": {
                "ocfDeviceType": "oic.d.washer",
                "name": "[washer] Samsung",
                "specVersion": "core.1.1.0",
                "verticalDomainSpecVersion": "1.2.1",
                "manufacturerName": "Samsung Electronics",
                "modelNumber": "DA_WM_TP1_21_COMMON|20233742|20000001001711000AAB020200000000",
                "platformVersion": "DAWIT 2.0",
                "platformOS": "TizenRT 3.1",
                "hwVersion": "Realtek",
                "firmwareVersion": "DA_WM_TP1_21_COMMON_30230810",
                "vendorId": "DA-WM-WM-01011",
                "vendorResourceClientServerVersion": "Realtek Release 3.1.230222",
                "lastSignupTime": "2023-11-15T23:54:28.733137Z",
            },
            "type": "OCF",
            "restrictionTier": 0,
            "allowed": [],
            "executionContext": "CLOUD",
        },
        {
            "deviceId": "4f5afedb-4d9c-66d4-7a37-2b3200a9d55b",
            "name": "[dryer] Samsung",
            "label": "Dryer",
            "manufacturerName": "Samsung Electronics",
            "presentationId": "DA-WM-WD-01011",
            "deviceManufacturerCode": "Samsung Electronics",
            "locationId": "e0cc1d23-ceba-40aa-9121-db1134002353",
            "ownerId": "50ed6115-a30c-a7d6-af51-9e96fc5ac1b5",
            "roomId": "568ea0cd-e641-44c4-9a61-3c5c5748e496",
            "deviceTypeName": "Samsung OCF Dryer",
            "components": [
                {
                    "id": "main",
                    "label": "main",
                    "capabilities": [
                        {"id": "ocf", "version": 1},
                        {"id": "execute", "version": 1},
                        {"id": "refresh", "version": 1},
                        {"id": "switch", "version": 1},
                        {"id": "remoteControlStatus", "version": 1},
                        {"id": "dryerOperatingState", "version": 1},
                        {"id": "powerConsumptionReport", "version": 1},
                        {"id": "demandResponseLoadControl", "version": 1},
                        {"id": "custom.disabledCapabilities", "version": 1},
                        {"id": "custom.dryerDryLevel", "version": 1},
                        {"id": "custom.dryerWrinklePrevent", "version": 1},
                        {"id": "custom.energyType", "version": 1},
                        {"id": "custom.jobBeginningStatus", "version": 1},
                        {"id": "custom.supportedOptions", "version": 1},
                        {"id": "samsungce.softwareUpdate", "version": 1},
                        {"id": "samsungce.detergentOrder", "version": 1},
                        {"id": "samsungce.detergentState", "version": 1},
                        {"id": "samsungce.deviceIdentification", "version": 1},
                        {"id": "samsungce.driverVersion", "version": 1},
                        {"id": "samsungce.dryerAutoCycleLink", "version": 1},
                        {"id": "samsungce.dryerCycle", "version": 1},
                        {"id": "samsungce.dryerCyclePreset", "version": 1},
                        {"id": "samsungce.dryerDelayEnd", "version": 1},
                        {"id": "samsungce.dryerDryingTemperature", "version": 1},
                        {"id": "samsungce.dryerDryingTime", "version": 1},
                        {"id": "samsungce.dryerFreezePrevent", "version": 1},
                        {"id": "samsungce.dryerLabelScanCyclePreset", "version": 1},
                        {"id": "samsungce.dryerOperatingState", "version": 1},
                        {"id": "samsungce.kidsLock", "version": 1},
                        {"id": "samsungce.welcomeMessage", "version": 1},
                        {"id": "samsungce.clothingExtraCare", "version": 1},
                        {"id": "sec.diagnosticsInformation", "version": 1},
                        {"id": "sec.wifiConfiguration", "version": 1},
                    ],
                    "categories": [{"name": "Dryer", "categoryType": "manufacturer"}],
                },
                {"id": "hca.main", "label": "hca.main", "capabilities": [{"id": "hca.dryerMode", "version": 1}], "categories": [{"name": "Other", "categoryType": "manufacturer"}]},
            ],
            "createTime": "2023-11-15T23:58:46.740Z",
            "profile": {"id": "0eddea8c-9d4e-3eaa-a7aa-3331b88be4d3"},
            "ocf": {
                "ocfDeviceType": "oic.d.dryer",
                "name": "[dryer] Samsung",
                "specVersion": "core.1.1.0",
                "verticalDomainSpecVersion": "1.2.1",
                "manufacturerName": "Samsung Electronics",
                "modelNumber": "DA_WM_TP1_21_COMMON|20233742|30000001001611000AAB030200000000",
                "platformVersion": "DAWIT 2.0",
                "platformOS": "TizenRT 3.1",
                "hwVersion": "Realtek",
                "firmwareVersion": "DA_WM_TP1_21_COMMON_30230810",
                "vendorId": "DA-WM-WD-01011",
                "vendorResourceClientServerVersion": "Realtek Release 3.1.230222",
                "lastSignupTime": "2023-11-15T23:58:42.110977Z",
            },
            "type": "OCF",
            "restrictionTier": 0,
            "allowed": [],
            "executionContext": "CLOUD",
        },
    ],
    "_links": {},
}
