
message = "VISUALLY INSPECT FOR WEAR, IMPROPER ALIGNMENT, OR BUILDUP OF FOREIGN MATERIALS ON THE SIDES OF THE BELT, AND ON INFEED AND DISCHARGE ENDS OF SORTER"

msg_output =  message.lower();

print(msg_output)